### ISSUE TITLE
Convert to OpenShift Template

### ISSUE THREAD

**Issue by chrisjsimpson** [chrisjsimpson/obp-kubernetes#8]
- Is an openshift template needed? Or can we just use the standard kubernetes yaml 
 in this repo? (https://github.com/chrisjsimpson/obp-kubernetes/blob/master/obpapi_k8s.yaml) 
Openshift templates docs: 
https://docs.openshift.com/container-platform/3.5/dev_guide/templates.html
- How does OpenShift handle Ingress, differences between Kubernetes Ingress Controllers and OpenShift, are they interoperable?

**Comment by chrisjsimpson** [comment]
Here is a revised yaml specific to Openshift template documentation:

- It basically involves wrapping everything in `kind: "Template"`
- The image chrisjsimpson/obpapi-kube needs to be revised to account for Openshift random user id, just like the older obp:minimal image does.

```
kind: "Template"
apiVersion: v1
metadata:
  name: "obp-api-example"
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: postgres-credentials
    type: Opaque
    data:
      postgres_user: cG9zdGdyZXM= #postgres
      postgres_password: cGFzc3dvcmQ= #password
      postgres_db_name: cG9zdGdyZXM= #postgres
      jdbc_driver: b3JnLnBvc3RncmVzcWwuRHJpdmVy # org.postgresql.Driver
      jdbc_url: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXMtc2VydmljZTo1NDMyL3Bvc3RncmVzP3VzZXI9cG9zdGdyZXMmcGFzc3dvcmQ9cGFzc3dvcmQ= # jdbc:postgresql://postgres-service:5432/postgres?user=postgres&password=password

  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata: 
        name: postgres-volume-claim
    spec:
        accessModes:
            - ReadWriteOnce
        volumeMode: Filesystem
        resources:
            requests:
                storage: 1Gi
        selector:
           matchLabels: 
                release: "stable"

  - kind: Service
    apiVersion: v1
    metadata:
        name: obpapi-service
    spec:
        selector:
            app: obpapi
        ports:
        - name: http
          protocol: TCP
          port: 80
          targetPort: 8080
        - name: postgres
          protocol: TCP
          port: 5432
          targetPort: 5432
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
        name: obp-deployment
        labels:
            app: obpapi
    spec:
        replicas: 1
        selector:
            matchLabels:
                app: obpapi
        template:
            metadata:
                labels:
                    app: obpapi
            spec:
                containers:
                - name: obpapi
                  image: chrisjsimpson/obpapi-kube # docker build -t obpapi-kube .
                  env:
                    - name: DB_DRIVER
                      valueFrom: 
                        secretKeyRef: 
                         name: postgres-credentials
                         key: jdbc_driver
                    - name: DB_URL
                      valueFrom: 
                        secretKeyRef: 
                         name: postgres-credentials
                         key: jdbc_url
                  ports:
                  - containerPort: 8080
                    name: http
                  - containerPort: 5432
                    name: postgres

  - kind: Service  
    apiVersion: v1
    metadata:
        name: postgres-service
    spec:
        selector:
            app: postgres
        ports:
        - protocol: TCP
          port: 5432
          targetPort: 5432

  - kind: Deployment
    apiVersion: apps/v1
    metadata:
        name: postgres
        labels:
            app: postgres
    spec:
        replicas: 1
        selector:
            matchLabels:
                app: postgres
        template:
            metadata:
                labels:
                    app: postgres
            spec:
                containers:
                - name: postgres
                  image: postgres:11.1-alpine
                  env: 
                    - name: POSTGRES_USER
                      valueFrom:
                        secretKeyRef:
                         name: postgres-credentials
                         key: postgres_user
                    - name: POSTGRES_PASSWORD
                      valueFrom:
                        secretKeyRef: 
                         name: postgres-credentials
                         key: postgres_password
                    - name: POSTGRES_DB
                      valueFrom:
                        secretKeyRef: 
                         name: postgres-credentials
                         key: postgres_db_name
                  volumeMounts:
                  - name: postgres-volume
                    mountPath: "/var/lib/postgresql/data"
                  ports:
                  - containerPort: 5432
                volumes:
                    - name: postgres-volume
                      persistentVolumeClaim:
                        claimName: postgres-volume-claim
```
